# Generated by Django 2.2.7 on 2019-12-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntable', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
